/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}


group = "gama.kernel"
version = "2.0.0-SNAPSHOT"
description = "gama.dependencies"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

dependencies {
    // api() will allow to expose the following dependencies to the modules that depend on gama.dependencies
    // https://www.baeldung.com/gradle-implementation-vs-compile#best-practices-for-gradle-dependency-management

    api(project(":gama.kernel:gama.dev"))
    api(project(":gama.kernel:gama.annotations"))

    api("com.google.inject:guice:4.0-beta5")
    compileOnlyApi("org.osgi:org.osgi.framework:1.10.0")

    api(files("./protobuf-java-3.6.1.jar"))

    // We ignore the 3.4.0 version because the com.google.protobuf.GeneratedMessageLite.MethodToInvoke
    // enum has less values than the 3.6.1 version, which causes compilations problems

    val ignoredFiles = listOf("protobuf-java-3.4.0.jar")

    // 👇 put the directories containing the jars you want to include
    listOf(
        "./geotools", "./jaxb", "./jfreechart", "./jgrapht 1.5.1",
        "./streamex", "./svgsalamander1.1.1", "./jts", "./jsr 363",
        "./commons-math3-3.6.1.jar", "./moeaframework-2.13.jar", 
    ).forEach { path ->
        api(
            fileTree(mapOf(
                "dir" to "$path", 
                "include" to listOf("*.jar"),
                "exclude" to ignoredFiles
            ))
        )
    }
    
    
}

tasks {
    jar {
        manifest {  
            from ("META-INF/MANIFEST.MF")
        }
    }
}


tasks.named<Jar>("jar") {
    dependsOn(":gama.kernel:gama.annotations:jar")
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(configurations.runtimeClasspath.get().filter { it.name.endsWith(".jar") }.map { zipTree(it) })
}


sourceSets.main {
    java {
        setSrcDirs(listOf("src"))
    }
    /*resources {
        setSrcDirs(listOf("resources"))
    }*/
}

