/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

group = "gama.kernel"
version = "2.0.0-SNAPSHOT"
description = "gama.dev"
java.sourceCompatibility = JavaVersion.VERSION_17


tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.jar {
    manifest {
        from ("META-INF/MANIFEST.MF")
    }
}

sourceSets {
    main {
        java {
            setSrcDirs(listOf("src"))
        }
    }
}

