/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("dev.equo.p2deps") version "1.7.2"
//    id("org.standardout.bnd-platform") version "1.7.0"
}

group = "gama.kernel"
version = "2.0.0-SNAPSHOT"
description = "gama.core"
//java.sourceCompatibility = JavaVersion.VERSION_17


p2deps {
    into("implementation") {
        // https://github.com/equodev/equo-ide/blob/main/P2_MULTITOOL.md for more info
        // we download eclipse RCP
        p2repo("https://download.eclipse.org/eclipse/updates/4.26/")

        listOf(
            "org.eclipse.emf.ecore",
            "org.eclipse.emf.common",
            "org.eclipse.core.filesystem",
            "org.eclipse.core.runtime",
            "org.eclipse.core.resources",
//            "org.apache.commons.compress" // It cannot be found for some reason, so it goes into dependencies
        ).forEach{
            install(it)
        }
    }
}

dependencies { 
    implementation(project(":gama.kernel:gama.dependencies"))

    implementation("org.apache.commons:commons-compress:1.21")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}

tasks.jar {
    manifest {
        from("META-INF/MANIFEST.MF")
    }
}
//
//sourceSets {
//    main {
//        java {
//            srcDirs("src")
//        }
//    }
//}

